const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const storage = fs.readFileSync(path.join(root, 'profile-storage.js'), 'utf8');
const styles = fs.readFileSync(path.join(root, 'styles.css'), 'utf8');

assert.match(html, /data-view="pantry"/);
assert.match(html, /id="addManyPantryItemsBtn"/);
assert.match(html, /id="pantryBulkDelete"/);
assert.match(html, /id="movePurchasedToPantryBtn"/);
assert.match(app, /id="usePantryIngredientsBtn"/);
assert.match(app, /function movePurchasedToPantry/);
assert.match(app, /function addBulkPantryItems/);
assert.match(app, /function deleteSelectedPantryItems/);
assert.match(app, /function checkPantryRestock/);
assert.match(app, /source:'Pantry restock'/);
assert.match(app, /function confirmUsePantryIngredients/);
assert.match(app, /PANTRY_CONVERSION_PROFILES/);
assert.match(app, /'flour-all-purpose':\{[^}]+gramsPerCup:120/);
assert.match(app, /'salt-table':\{[^}]+gramsPerCup:288/);
assert.match(app, /'salt-kosher':\{[^}]+gramsPerCup:230/);
assert.match(app, /'salt-sea':\{[^}]+gramsPerCup:288/);
assert.match(app, /'salt-himalayan':\{[^}]+gramsPerCup:288/);
assert.match(app, /function convertPantryAmount/);
assert.match(app, /gallons:16,quarts:4,pints:2/);
assert.match(app, /function pantryIngredientMatchKey/);
assert.match(html, /id="pantryConversionProfile"/);
assert.match(html, /id="pantryConversionPreview"/);
assert.match(html, /id="pantryGroupFilter"/);
assert.match(app, /state[.]pantryItems=state[.]pantryItems[.]filter/);
assert.match(app, /function recipePantryReadiness/);
assert.match(app, /function ingredientPantryReadiness/);
assert.match(app, /pantryReadinessMarker/);
assert.match(styles, /[.]pantry-readiness-green/);
assert.match(styles, /:root\[data-theme="dark"\] [.]pantry-readiness-yellow/);
assert.match(styles, /[.]pantry-compact-action/);
assert.match(storage, /pantryItems: \[\]/);
assert.match(storage, /pantryItems: clone\(this[.]activeProfile[.]pantryItems/);
assert.match(styles, /[.]pantry-row\{/);

console.log('Pantry regression passed: local inventory, bulk entry/removal, shopping transfer, recipe use, restocking, and profile persistence are wired.');
